# Generated by Django 4.2.5 on 2024-05-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSphere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStats',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SocialSphere.event')),
                ('total_likes', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_visitors', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contentmanager',
            options={},
        ),
        migrations.RemoveField(
            model_name='contentmanager',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='contentmanager',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='event',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reacts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='views',
        ),
        migrations.AlterField(
            model_name='event',
            name='caption',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialSphere.event')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialSphere.event')),
            ],
        ),
    ]
