# Generated by Django 4.2.5 on 2024-04-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSphere', '0002_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='EventPhoto',
        ),
        migrations.RemoveField(
            model_name='event',
            name='photo_or_video',
        ),
    ]
