# Generated by Django 4.2.5 on 2024-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSphere', '0003_rename_photo_eventphoto_remove_event_photo_or_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_or_video',
            field=models.ImageField(default='background.png', upload_to='events/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventPhoto',
        ),
    ]
