# Generated by Django 4.2.5 on 2024-06-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSphere', '0003_rename_photo_or_video_event_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmanager',
            options={'verbose_name': 'Content Manager', 'verbose_name_plural': 'Content Managers'},
        ),
    ]
