# Generated by Django 4.2.5 on 2024-06-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSphere', '0004_alter_contentmanager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmanager',
            options={},
        ),
    ]
