# Generated by Django 4.2.5 on 2024-06-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSphere', '0005_alter_contentmanager_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contentmanager',
            table='content_manager',
        ),
    ]
