# Generated by Django 4.2.5 on 2024-06-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSphere', '0006_alter_contentmanager_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contentmanager',
            table=None,
        ),
    ]
