# Generated by Django 4.2.14 on 2024-10-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSphere', '0008_alter_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar_style',
            field=models.CharField(default='pixel-art', max_length=50),
        ),
    ]
